/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Informe_controlador;
import Modelo.Enums.Stands;
import Modelo.LibrosTS;
import Vista.UtilComponentes.UtilComponentes;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mac
 */
public class Frm_Biblioteca extends javax.swing.JFrame {

    DefaultTableModel m = new DefaultTableModel();
    private Informe_controlador ic = new Informe_controlador();
    int[] total_libros = new int[5];

    /**
     * Creates new form Frm_Biblioteca
     */
    public Frm_Biblioteca() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        txttotal.setEnabled(false);

        limpiar();
        
        modeloTabla();
        cbxTematica.removeAllItems();

    }

    private void limpiar() {
        //cambiar nombre
        ic.crearArregloLibro(5);
        UtilComponentes.cargarComboStands(cbxstand);
        UtilComponentes.cargarComboTematica(cbxTematica, ic);

        ic.crearArregloInforme(5, 5);
    }

    private void modeloTabla() {

        m.addColumn("Tematica");
        for (int i = 0; i < 3; i++) {
            m.addColumn(cbxstand.getItemAt(i));
        }
        m.addColumn("Total");
        tbl.setModel(m);
        tbl.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumlibros = new javax.swing.JTextField();
        cbxstand = new javax.swing.JComboBox<>();
        btnTematica = new javax.swing.JButton();
        cbxTematica = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        labeltotal = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tematica:");

        jLabel2.setText("Numero de Stand:");

        jLabel3.setText("Numero de Libros:");

        txtNumlibros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumlibrosKeyTyped(evt);
            }
        });

        cbxstand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTematica.setText("Añadir Tematica");
        btnTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTematicaActionPerformed(evt);
            }
        });

        cbxTematica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAgregar.setText("Agregar a la Tabla");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl);

        labeltotal.setText("total");

        jButton1.setText("mayor num libros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxTematica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTematica)))
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxstand, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumlibros, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labeltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(321, 321, 321))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtNumlibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxstand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTematica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeltotal)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTematicaActionPerformed
        // TODO add your handling code here:
        String tematica = JOptionPane.showInputDialog("Ingrese la tematica");
        int pos = UtilComponentes.possNull(ic);

        if (pos != -1) {
            if (tbl.getRowCount() < 5) {

                //nuevo
                ic.getLibrosTS().setTematica(tematica);

                ic.getLibrossTS_a()[pos] = ic.getLibrosTemp(ic.getLibrosTS());
                UtilComponentes.cargarComboTematica(cbxTematica, ic);
                ic.setLibrosTS(null);
                modeloTablaFilaConductor();
                tbl.setValueAt(tematica, pos, 0);
            } else {
                JOptionPane.showMessageDialog(this, "Solo se permite 5 Tematicas");
            }

        } else {
            System.out.println("no hay espacio");
        }

    }//GEN-LAST:event_btnTematicaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        if (txtNumlibros.getText().equals("") || cbxTematica.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Por favor llene todos los campos \n-Añadir y seleccionar una tematica\n-Ingresar numero de libros");
        } else {
            cargarInforme();
            int total = 0;
            int aux = 0;
            int count = 0;

            for (int i = 0; i < cbxTematica.getItemCount(); i++) {

                //
                for (int j = 0; j < 3; j++) {
                    if ((tbl.getValueAt(i, j + 1)) != null) {
                        //  System.out.println("ff "+Integer.parseInt((String.valueOf(tabla.getValueAt(i, j)))));
                        count = Integer.parseInt((String.valueOf(tbl.getValueAt(i, j + 1))));

                        total = total + count;
                    }
                }
                tbl.setValueAt(total, i, 4);
                total_libros[i] = total;
                aux = aux + total;
                total = 0;

                txttotal.setText(String.valueOf(aux));
            }

            for (int i = 0; i < total_libros.length; i++) {
                System.out.println("libos por tematica " + total_libros[i]);
            }

        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int aux = 0;

        for (int i = 0; i < cbxTematica.getItemCount(); i++) {
            for (int j = 1; j < 4; j++) {
                // System.out.println("tbla.getValueAt(0, i) " + tbl.getValueAt(i, j));
                if (tbl.getValueAt(i, j) == "") {
                    aux = 1;
                }
            }
        }
        if (aux == 1) {
            JOptionPane.showMessageDialog(this, "No se han llenadotodos los valores");
        } else {
            MenorMayorNumlibros();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNumlibrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumlibrosKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if ((!Character.isDigit(car)) && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se permite el ingreso de numeros");
        }
    }//GEN-LAST:event_txtNumlibrosKeyTyped

    private void MenorMayorNumlibros() {
        int menor = total_libros[0];
        int mayor = total_libros[0];
        int cont = 0;
        String infSup = "";

        for (int i = 0; i < total_libros.length; i++) {
            System.out.println("t l " + total_libros[i]);
            if (total_libros[i] < menor) {
                menor = total_libros[i];
            }

            if (total_libros[i] > mayor) {
                mayor = total_libros[i];
            }
        }
        infSup += "TEMATICAS CON -MENOR- NUMERO DE LIBROS\n";
        for (int i = 0; i < total_libros.length; i++) {
            if (ic.getLibrossTS_a()[i] != null) {
                if (menor == total_libros[i]) {
                    infSup = infSup + "El menor numero de libros es de - " + menor + " - que corresponde a la tematica  " + ic.getLibrossTS_a()[i] + " -\n";
                }
            } else {
                infSup = "se debe ingresar todas las tematicas para poder comparar\nVerifique si ha ingresado las respectivas tematicas";
            }

        }

        infSup = infSup + "\n\nTEMATICAS CON -MAYOR- NUMERO DE LIBROS\n";
        for (int i = 0; i < total_libros.length; i++) {
            if (ic.getLibrossTS_a()[i] != null) {
                if (mayor == total_libros[i]) {
                    infSup = infSup + "El mayor numero de libros es de - " + mayor + " - que corresponde a la tematica  " + ic.getLibrossTS_a()[i] + " -\n";
                }
            } else {
                infSup = "se debe ingresar todas las tematicas para poder comparar\nVerifique si ha ingresado todas las tematicas";

            }
        }

        JOptionPane.showMessageDialog(this, infSup);

    }

    public void cargarInforme() {

        ic.getInforme().setStands((Stands) cbxstand.getSelectedItem());
        ic.getInforme().setLibrosTS((LibrosTS) cbxTematica.getSelectedItem());
        ic.getInforme().setNum_libros_tematica(Integer.parseInt(txtNumlibros.getText()));
        ic.getInformes()[cbxTematica.getSelectedIndex()][cbxstand.getSelectedIndex()] = ic.getInforme(ic.getInforme());
        tbl.setValueAt(txtNumlibros.getText(), cbxTematica.getSelectedIndex(), cbxstand.getSelectedIndex() + 1);
        //tabla.setValueAt(ic.getHorario().getKilometros_Dia(), cbxNameC.getSelectedIndex(), cbxDias.getSelectedIndex() + 1); 
    }

    private void modeloTablaFilaConductor() {
        if (tbl.getRowCount() <= 4) {

            String[] Datos = new String[5];
            for (int i = 0; i < 1; i++) {
                Datos[i] = "";
            }
            m.addRow(Datos);
            tbl.setModel(m);
            tbl.updateUI();
        } else {
            JOptionPane.showMessageDialog(this, "Solo se permite 5 conductores");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnTematica;
    private javax.swing.JComboBox<String> cbxTematica;
    private javax.swing.JComboBox<String> cbxstand;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labeltotal;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtNumlibros;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
